### PR TITLE
Avoid imaginary roe average sound speed

### LINKED ISSUE #555: HLLC wavespeeds are not computed correctly if cs_tilde is imaginary
**Describe the bug**
For some left and right states, it is possible that the Roe-average sound speed is imaginary:
https://github.com/quokka-astro/quokka/blob/fcde1aa11205ed64365e42ce7e084a9964aa7e9f/src/HLLC.hpp#L58

Since `std::min` behaves differently for different compilers when one argument is NAN (in particular, gcc returns a the non-NAN argument while Clang returns NAN), we have problems when using Clang-based compilers to run problems that have interfaces where the Roe average is not defined:
https://github.com/quokka-astro/quokka/blob/fcde1aa11205ed64365e42ce7e084a9964aa7e9f/src/HLLC.hpp#L64

A reasonable solution would be to check whether $\tilde c_s^2$ is positive, and, if not, use the arithmetic average of the left and right sound speeds.

**To Reproduce**
1. Compile the PopIII problem with an Clang-based compiler.
2. Run this problem for one timestep.
3. Print out the HLLC wavespeeds for at each interface.
4. Observe NAN values.

**Additional context**
Since the AMD GPU compiler is based on Clang, it also has this problem, and is the reason the hydro update behaves differently on AMD GPUs.

Thanks to @psharda for discovering this after a truly exceptional debugging effort.

### PR DESCRIPTION
**Pull request by psharda**
### Description
There can be instances when the Roe-averaged sound speed (`cs_tilde` in `HLLC.hpp`) can be negative. In such cases, the current implementation will generate a NAN cs_tilde, which is handled differently by different compilers (e.g., GCC versus HIPCC). This was one of the causes of StarCluster and PopIII problems failing on HIPCC-based CPUs and AMD GPUs.

### Related issues
Fixes #555.

### Checklist
_Before this pull request can be reviewed, all of these tasks should be completed. Denote completed tasks with an `x` inside the square brackets `[ ]` in the Markdown source below:_
- [x] I have added a description (see above).
- [x] I have added a link to any related issues see (see above).
- [x] I have read the [Contributing Guide](https://github.com/quokka-astro/quokka/blob/development/CONTRIBUTING.md).
- [ ] I have added tests for any new physics that this PR adds to the code.
- [x] I have tested this PR on my local computer and all tests pass.
- [x] I have manually triggered the GPU tests with the magic comment `/azp run`.
- [x] I have requested a reviewer for this PR.

### CODE REVIEW

File: src/HLLC.hpp [hunk 1]
```diff
@@ -54,8 +54,14 @@ AMREX_FORCE_INLINE AMREX_GPU_DEVICE auto HLLC(quokka::HydroState<N_scalars, N_ms
 		// equation A.5b of Kershaw+1998
 		const double C_tilde_P = 0.5 * ((sL.Eint / sL.rho) * drdp_L + (sR.Eint / sR.rho) * drdp_R + sL.rho * dedp_L + sR.rho * dedp_R);
 
-		// equation 4.12 of Kershaw+1998
-		cs_tilde = std::sqrt((1.0 / C_tilde_P) * (H_tilde - 0.5 * vsq_tilde - C_tilde_rho));
+		// avoid NAN cs_tilde
+		if (H_tilde - 0.5 * vsq_tilde - C_tilde_rho < 0) {
```
Comment (BenWibking) [inline src/HLLC.hpp]: I think it would be better to check whether this is less than _or equal to_ 0. A zero value produces a non-NaN cs_tilde, but has other problems.

A minor optimization, but can you extract this to a separate variable to avoid computing it twice?

File: src/HLLC.hpp [hunk 2]
```diff
@@ -54,8 +54,14 @@ AMREX_FORCE_INLINE AMREX_GPU_DEVICE auto HLLC(quokka::HydroState<N_scalars, N_ms
...
+			// fall back to the gamma=1 case
```
Comment (BenWibking) [inline src/HLLC.hpp]: I think this comment is a bit confusing. This is the same code used when $\gamma = 1$, but is not conceptually related to having an isothermal equation of state. It's just an arithmetic average of the left and right sound speeds.

File: src/HLLC.hpp [hunk 3]
```diff
@@ -54,8 +54,15 @@ AMREX_FORCE_INLINE AMREX_GPU_DEVICE auto HLLC(quokka::HydroState<N_scalars, N_ms
...
-		// equation 4.12 of Kershaw+1998
-		cs_tilde = std::sqrt((1.0 / C_tilde_P) * (H_tilde - 0.5 * vsq_tilde - C_tilde_rho));
+		// avoid NAN cs_tilde
+		const double cs_exp = H_tilde - 0.5 * vsq_tilde - C_tilde_rho;
+		if (cs_exp <= 0) {
+			// take the average of the left and right states
+			cs_tilde = 0.5 * (sL.cs + sR.cs);
+		} else {
+			// equation 4.12 of Kershaw+1998
+			cs_tilde = std::sqrt((1.0 / C_tilde_P) * cs_exp);
```
Comment (BenWibking) [inline src/HLLC.hpp]: You could simplify this to `cs_tilde = std::sqrt(cs_exp / C_tilde_P)`.

**Review by BenWibking — CHANGES_REQUESTED** [review]
Ok, looks good. I've noted one suggestion inline that will avoid an extra floating-point operation when the compiler interprets the parentheses strictly.

**Review by BenWibking — APPROVED** [review]
