### PR TITLE
Make assertion work in the exchange step and dust temperature solution step 

### LINKED ISSUE #543: amrex::Abort does not unconditionally abort on GPU
**Describe the bug**
We have been relying on `amrex::Abort` to unconditionally abort the code when called from GPU code. However, this only works when compiled in debug mode (or with additional compiler flags).

We need to rewrite the error handling code for iterative solves so that it correctly handles errors when `-DCMAKE_BUILD_TYPE=Release` is used (the default).

The Quokka documentation incorrectly describes `amrex::Abort` based on the old AMReX documentation (which was incorrect): https://quokka-astro.github.io/quokka/error_checking.html

**To Reproduce**
1. Compile the PopIII problem for GPU
2. It should crash with a VODE failure at timestep 58
3. Observe that it does not.

**Additional context**
The AMReX documentation was recently changed (October 2023) to reflect this new behavior, but this change was not communicated to the user community: https://github.com/AMReX-Codes/amrex/pull/3605.

**This affects both the Newton-Raphson solve used by the radiation code as well as the Microphysics chemistry integrator.**
cc @psharda @chongchonghe

### PR DESCRIPTION
**Pull request by chongchonghe**
### Description

A fix to #543 : make the Newton-Raphson iteration return a flag and check it on host. 

More changes:
- Change `maxIter` from 400 to 50. 50 iterations should be more than enough. If it doesn't converge in less than 50 steps, it probably never will. 

### Related issues
Fixes #543 

### Checklist
_Before this pull request can be reviewed, all of these tasks should be completed. Denote completed tasks with an `x` inside the square brackets `[ ]` in the Markdown source below:_
- [x] I have added a description (see above).
- [x] I have added a link to any related issues see (see above).
- [x] I have read the [Contributing Guide](https://github.com/quokka-astro/quokka/blob/development/CONTRIBUTING.md).
- [ ] I have added tests for any new physics that this PR adds to the code.
- [x] I have tested this PR on my local computer and all tests pass.
- [x] I have manually triggered the GPU tests with the magic comment `/azp run`.
- [x] I have requested a reviewer for this PR.

### CODE REVIEW

File: src/radiation/radiation_system.hpp [hunk 1]
```diff
@@ -1678,6 +1695,10 @@ void RadSystem<problem_t>::AddSourceTerms(array_t &consVar, arrayconst_t &radEne
 				} // END NEWTON-RAPHSON LOOP
 
 				AMREX_ALWAYS_ASSERT_WITH_MESSAGE(n < maxIter, "Newton-Raphson iteration failed to converge!");
```
Comment (BenWibking) [inline src/radiation/radiation_system.hpp]: Is there a reason to leave the old abort statements in the code?

Comment (chongchonghe) [reply src/radiation/radiation_system.hpp]: I kept it there just to let abort earlier on CPU. This is particularly useful for development because you know exactly when and where it aborts.

Comment (BenWibking) [reply src/radiation/radiation_system.hpp]: Can you change it to `AMREX_ASSERT_WITH_MESSAGE`? Then it only has different behavior when `-DCMAKE_BUILD_TYPE=Debug`, rather than CPU vs GPU (which I think is confusing).

File: src/radiation/radiation_system.hpp [hunk 2]
```diff
@@ -1962,6 +1983,15 @@ void RadSystem<problem_t>::AddSourceTerms(array_t &consVar, arrayconst_t &radEne
 			consNew(i, j, k, x3RadFlux_index + numRadVars_ * g) = Frad_t1[2][g];
 		}
 	});
+
+	const int nf_coupling = *(num_failed_coupling.copyToHost());
+	const int nf_dust = *(num_failed_dust.copyToHost());
```
Comment (BenWibking) [inline src/radiation/radiation_system.hpp]: I'm not sure whether `copyToHost` is asynchronous or not. Can you check this? If it's asynchronous, then there is a race condition here: we don't know whether the GPU will write to the memory location before the CPU reads it.

For performance reasons, it would be better to do this after all of the FABs have been processed, rather than after each FAB. Otherwise, the GPU will have to synchronize with the CPU after each FAB (in order to guarantee that the CPU is reading the up-to-date value of each variable). This synchronization can be relatively expensive.

File: src/radiation/radiation_system.hpp (hunk 1 above)
Comment (chongchonghe) [reply src/radiation/radiation_system.hpp]: OK.

File: src/radiation/radiation_system.hpp (hunk 2 above)
Comment (chongchonghe) [reply src/radiation/radiation_system.hpp]: I tested this PR on gadi GPU and it indeed aborted as expected when I set max_Iter to a small number.

Comment (chongchonghe) [reply src/radiation/radiation_system.hpp]: > For performance reasons, it would be better to do this after all of the FABs have been processed, rather than after each FAB.

I'll see if I can do that. My idea is to set a counter in `QuokkaSimulation<problem_t>::subcycleRadiationAtLevel` and pass it to `operatorSplitSourceTerms` then `AddSourceTerms`.

Comment (BenWibking) [reply src/radiation/radiation_system.hpp]: Ok, it's good to also check the source code: https://github.com/AMReX-Codes/amrex/blob/c061a14011d4d58755f330d15a20f7243863a90d/Src/Base/AMReX_GpuBuffer.H#L91.

There is still a potential performance issue. Maybe you could allocate the `GpuBuffer`s in the calling function, and then check the result there?

Comment (chongchonghe) [reply src/radiation/radiation_system.hpp]: Updated.

I'm not sure what you mean by "calling function". Now, `copyToHost` is called once per radiation cycling. This should be optimal enough. I also tested it on gadi GPU and the code aborted as expected when set to.

**Review by BenWibking — APPROVED** [review]
