### PR TITLE
Fix small b-field degeneracy in HLLD solver

### LINKED ISSUE #746: add small fix to HLLD solver from Athena++
**Describe the bug**
One of the degeneracy checks in the HLLD solver should not be used. See: https://github.com/PrincetonUniversity/athena/pull/620

**Additional context**
From https://github.com/PrincetonUniversity/athena/pull/620:

> It turned out that we should not remove the double-star states even when the normal magnetic field bx is very weak. If this branch is selected when bx is actually non-zero, it may return unphysical flux. In fact, this check is not mentioned in Miyoshi & Kusano 2005 but already existed in the old Athena,
> 
> I do not think this has affected many people, as this is problematic only when the magnetic fields are very weak and the flow is not smooth. The probability that this branch is selected is very low in a realistic flow.

### PR DESCRIPTION
**Pull request by AstroKriel**
### Description
This PR removes the ad-hoc "weak magnetic field" degeneracy branch in the HLLD MHD Riemann solver, where the double-star states were collapsed onto the single-star states when the normal field component was very weak. The double-star states are now always computed using the Miyoshi & Kusano (2005) eqs. (59)–(63), bringing Quokka’s HLLD implementation in line with the Athena++/Parthenon implementation (see [Athena++'s PR discussion](https://github.com/PrincetonUniversity/athena/pull/620)). This should avoid unphysical fluxes in non-smooth regions when the field is weak, while leaving the rest of the solver unchanged. I have not added a dedicated correctness test for this change, but the logic now follows the published HLLD derivation and the upstream Athena++ fix.

### Related issues
Fixes https://github.com/quokka-astro/quokka/issues/746

### Checklist
- [x] I have added a description (see above).
- [x] I have added a link to any related issues (if applicable; see above).
- [x] I have read the [Contributing Guide](https://github.com/quokka-astro/quokka/blob/development/CONTRIBUTING.md).
- [ ] I have added tests for any new physics that this PR adds to the code.
- [ ] *(For quokka-astro org members)* I have manually triggered the GPU tests with the magic comment `/azp run`.

### CODE REVIEW

File: src/hydro/HLLD.hpp [hunk 1]
```diff
@@ -209,50 +209,50 @@ AMREX_FORCE_INLINE AMREX_GPU_DEVICE auto HLLD(quokka::HydroState<N_scalars, N_ms
...
-		// MK5: eqn (62)
-		tmp = rho_sum_inv * (rho_sqrt_L * u_star_R.bz + rho_sqrt_R * u_star_L.bz +
-				     bx_sign * rho_sqrt_L * rho_sqrt_R * ((u_star_R.mz * u_star_rho_inv_R) - (u_star_L.mz * u_star_rho_inv_L)));
-		u_dstar_L.bz = tmp;
-		u_dstar_R.bz = tmp;
-		// MK5: eqn (63)
-		tmp = spds[2] * bx + (u_dstar_L.my * u_dstar_L.by + u_dstar_L.mz * u_dstar_L.bz) / u_dstar_L.rho;
-		u_dstar_L.E = u_star_L.E - rho_sqrt_L * bx_sign * (vb_star_L - tmp);
-		u_dstar_R.E = u_star_R.E + rho_sqrt_R * bx_sign * (vb_star_R - tmp);
+	// if Bx is near zero, compute double-star states using MK5 eqns (59)–(63)
```
Comment (BenWibking) [inline src/hydro/HLLD.hpp]: This comment is not needed anymore, is it?

File: src/hydro/HLLD.hpp
Comment (BenWibking) [inline src/hydro/HLLD.hpp:16]: `DELTA` isn't needed anymore, is it?

**Review by BenWibking — CHANGES_REQUESTED** [review]

File: src/hydro/HLLD.hpp
Comment (AstroKriel) [reply src/hydro/HLLD.hpp:16]: It's used in a couple more places: lines 166 and 190.

File: src/hydro/HLLD.hpp (hunk 1 above)
Comment (AstroKriel) [reply src/hydro/HLLD.hpp]: I've removed the "if Bx is near zero" qualifier from the comment

Comment (BenWibking) [reply src/hydro/HLLD.hpp]: Can you push this change?

**Review by BenWibking — APPROVED** [review]
