### PR TITLE
retry hydro update if cooling solve fails

### LINKED ISSUE #372: retry hydro update when operator-split reactions fail
If the cooling or chemistry solve fails (due to, e.g. exceeding the maximum number of internal substeps), then the hydro step will just crash.

Instead, we should re-do the hydro update with a smaller timestep, just as is done for "bad" hydro updates.

### PR DESCRIPTION
**Pull request by BenWibking**
### Description
This triggers the retry mechanism for the hydro update if the cooling solve fails. This mirrors the behavior for the chemistry solve (#615).

### Related issues
Closes https://github.com/quokka-astro/quokka/issues/372.

### Checklist
_Before this pull request can be reviewed, all of these tasks should be completed. Denote completed tasks with an `x` inside the square brackets `[ ]` in the Markdown source below:_
- [x] I have added a description (see above).
- [x] I have added a link to any related issues see (see above).
- [x] I have read the [Contributing Guide](https://github.com/quokka-astro/quokka/blob/development/CONTRIBUTING.md).
- [ ] I have added tests for any new physics that this PR adds to the code.
- [x] I have tested this PR on my local computer and all tests pass.
- [x] I have manually triggered the GPU tests with the magic comment `/azp run`.
- [x] I have requested a reviewer for this PR.

### CODE REVIEW

File: src/GrackleLikeCooling.hpp [hunk 1]
```diff
@@ -309,14 +309,16 @@ template <typename problem_t> void computeCooling(amrex::MultiFab &mf, const Rea
...
-	int nmin = nsubstepsMF.min(0);
 	int nmax = nsubstepsMF.max(0);
 	Real navg = static_cast<Real>(nsubstepsMF.sum(0)) / static_cast<Real>(nsubstepsMF.boxArray().numPts());
-	amrex::Print() << fmt::format("\tcooling substeps (per cell): min {}, avg {}, max {}\n", nmin, navg, nmax);
+	amrex::Print() << fmt::format("\tcooling substeps (per cell): avg {}, max {}\n", navg, nmax);
 
+	// check if integration succeeded
 	if (nmax >= maxStepsODEIntegrate) {
-		amrex::Abort("Max steps exceeded in cooling solve!");
+		amrex::Print() << "\t[GrackleLikeCooling] Reaction ODE failure. Max steps exceeded in cooling solve!\n";
```
Comment (psharda) [inline src/GrackleLikeCooling.hpp]: It would be good to mention here that we will be retrying hydro now.

File: src/RadhydroSimulation.hpp [hunk 2]
```diff
@@ -509,21 +509,20 @@ template <typename problem_t> void RadhydroSimulation<problem_t>::addStrangSplit
 template <typename problem_t>
 auto RadhydroSimulation<problem_t>::addStrangSplitSourcesWithBuiltin(amrex::MultiFab &state, int lev, amrex::Real time, amrex::Real dt) -> bool
 {
-
-	// start by assuming chemistry burn is successful.
-	bool burn_success = true; // NOLINT
-
+	bool cool_success = true;
```
Comment (psharda) [inline src/RadhydroSimulation.hpp:513]: It would be good to add a comment before this line that says something similar to 'start by assuming chemistry burn is successful'

**Comment by psharda** [comment]
It would be good to edit these two comments to make it consistent for the user. I could not find a way to add a comment on these lines directly (perhaps github only allows providing comments on the lines you changed):

https://github.com/quokka-astro/quokka/blob/435e77cf8612c10746fc7cf8320133661a4e8470/src/RadhydroSimulation.hpp#L1038

https://github.com/quokka-astro/quokka/blob/435e77cf8612c10746fc7cf8320133661a4e8470/src/RadhydroSimulation.hpp#L1305

**Comment by BenWibking** [comment]
@psharda can you re-review?

**Review by psharda — APPROVED** [review]
