### PR TITLE
Fix the carbuncle problem in the HLLD solver

### LINKED ISSUE #528: add carbuncle fix to HLLD solver
**Describe the proposal**
The HLLD solver should include the same low-dissipation pressure correction and carbuncle correction that are currently included in the HLLC solver.

The relevant parts of the HLLC solver are:
- https://github.com/quokka-astro/quokka/blob/edc1dbcf2e22ae47dc2d78aa9b0b6d0966671bb6/src/HLLC.hpp#L93
- https://github.com/quokka-astro/quokka/blob/edc1dbcf2e22ae47dc2d78aa9b0b6d0966671bb6/src/HLLC.hpp#L82

**Additional context**
- Minoshima & Miyoshi, "A low-dissipation HLLD approximate Riemann solver for a very wide range of Mach numbers," JCP (2021), https://arxiv.org/abs/2108.04991.
- Athena++ implementation: https://github.com/PrincetonUniversity/athena/blob/master/src/hydro/rsolvers/mhd/lhlld.cpp

### PR DESCRIPTION
**Pull request by AstroKriel**
### Description
This PR mirrors the HLLC carbuncle fix, but for the HLLD solver: we apply the same transverse vel jump detector and damp the middle-speed pressure jump accordingly, with no other changes to HLLD’s star/dstar states. To test that the fix works correctly, I've duplicated the Quirk test with MHD enabled and B=0 (so HLLD is used internally). With this, the post-shock instability disappears and matches the HLLC reference (see attached figure of the before/after solution + the reference HLLC solution). Note, the low-Mach pressure correction is intentionally deferred for a follow-up PR.

carbuncle-fix-HLLD

### Related issues
Partially fixes https://github.com/quokka-astro/quokka/issues/528.

### Checklist
_Before this pull request can be reviewed, all of these tasks should be completed. Denote completed tasks with an `x` inside the square brackets `[ ]` in the Markdown source below:_
- [x] I have added a description (see above).
- [x] I have added a link to any related issues (if applicable; see above).
- [x] I have read the [Contributing Guide](https://github.com/quokka-astro/quokka/blob/development/CONTRIBUTING.md).
- [x] I have added tests for any new physics that this PR adds to the code.
- [x] *(For quokka-astro org members)* I have manually triggered the GPU tests with the magic comment `/azp run`.

### CODE REVIEW

**Review by markkrumholz — DISMISSED** [review]

File: src/hydro/HLLD.hpp [hunk 1]
```diff
@@ -116,9 +118,19 @@ AMREX_FORCE_INLINE AMREX_GPU_DEVICE auto HLLD(quokka::HydroState<N_scalars, N_ms
...
-	spds[2] = (siui_R * u_R.mx - siui_L * u_L.mx + (ptot_L - ptot_R)) / (siui_R * u_R.rho - siui_L * u_L.rho);
+	// carbuncle detector
+	const double max_spd = std::max(fspd_L, fspd_R);
+	const double para_v_jump = sL.u - sR.u; // negative -> compression
+	double theta = 1.0;
+	// tp := shock anisotropy, clamped to [0, 1], with theta = tp^4
+	const double denom_tp = std::max(1e-14, max_spd - std::min(perp_v_jump, 0.0));
+	double tp = (max_spd - std::min(para_v_jump, 0.0)) / denom_tp;
+	tp = std::max(tp, 0.0); // for completeness, but not strictly mathematically necessary
+	tp = std::min(tp, 1.0);
```
Comment (BenWibking) [inline src/hydro/HLLD.hpp]: This can be simplified to `std::clamp(tp, 0.0, 1.0)`

**Review by BenWibking — APPROVED** [review]
